### ISSUE TITLE
Hackintosh Dell 5566

### ISSUE THREAD

**Issue by objectiveice9883** [paulowender/Hackintosh-Dell-5566#1]
Bom dia amigo! Como está seu hack? Algum progresso nos itens que você não tinha conseguido? Tenho um exatamente igual o seu, e essa semana consegui rodar o Monterey nele. Supreendentemente funcionou muita coisa: Ethernet via RTL8100.kext, Wi-Fi que eu to utilizando um conector USB e está funcionando a contento, audio e microfone funcionando, o hack está até conseguindo ler a bateria, por incrível que pareça. O que ainda não consegui foi o trackpad e o brilho da tela (fica no máximo por padrão, e não consigo diminuir). Você teve sucesso com estes itens como? Consegue me ajudar?

Obrigado!!

**Comment by paulowender** [comment]
Boa noite amigo, no momento estou utilizando uma EFI Opencore e está funcionando muito bem praticamente tudo, exceto pelo Wi-Fi que funciona meia boca e o bluetooth que me passaram uma solução mas ainda não testei, assim que possível disponibilizo aqui, qualquer coisa pode me chamar no Telegram que te encaminho pra testar. Telegram: @paulowender
 ![image](https://user-images.githubusercontent.com/42776823/150445648-356da94b-1002-499a-8ded-f18c37718402.jpeg)

**Comment by paulowender** [comment]
Problemas citados solucionado utilizando o opencore, exceto pelo wifi que funciona apenas utilizando um dongle usb ou substituindo a placa de rede por um modelo compatível, caso seja necessário por favor abrir nova issue.
